spring:
  application:
    name: hystrix-client

  main:
    allow-bean-definition-overriding: true

server:
  port: 12211

eureka:
  client:
    serviceUrl.defaultZone: ${EUREKA_URI:http://localhost:8762/eureka}
